### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by owen590** [silver6wings/SilverQuant#2]
runfile('C:/py/ProjectQ/prod_sample.py', wdir='C:/py/ProjectQ')
subscribe_quote callback error: <function callback_sub_whole at 0x0000018E0707DE50>
Traceback (most recent call last):
  File "C:\py\ProjectQ\xtquant\xtdata.py", line 702, in subscribe_callback
    callback(datas)
  File "C:\py\ProjectQ\prod_sample.py", line 29, in callback_sub_whole
    read_date = load_json(path_dat)['date']
KeyError: 'date'
subscribe_quote callback error: <function callback_sub_whole at 0x0000018E0707DE50>
Traceback (most recent call last):
  File "C:\py\ProjectQ\xtquant\xtdata.py", line 702, in subscribe_callback
    callback(datas)
  File "C:\py\ProjectQ\prod_sample.py", line 29, in callback_sub_whole
    read_date = load_json(path_dat)['date']
KeyError: 'date'

**Comment by silver6wings** [comment]
Should have been fixed.
